version: '3'

services:

  app:
    image: gcr.io/d3hiring/d3hiring:latest
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=mysql://root:eFfzsYywAp9E@db:3306/d3hiring
    networks:
      - d3hiring-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=eFfzsYywAp9E
      - MYSQL_DATABASE=d3hiring
    ports:
      - "3307:3306"
    networks:
      - d3hiring-network
networks:
  d3hiring-network: